# Importing all the library

In [30]:
import numpy as np
import pandas as pd

# Defining the SigmoidPerceptron Class

In [51]:
class SigmoidPerceptron():

  def __init__(self, input_size):
    self.weight = np.random.randn(input_size)
    self.bias = np.random.randn(1)

  def sigmoid(self, z):
    return 1 / (1 + np.exp(-z))


  def predict(self, input):
    sum = np.dot(input, self.weight) + self.bias
    return self.sigmoid(sum)



  def fit(self, input, targets, learningrate, epochs):

    input_rows = len(input)

    for epoch in range(epochs):
      for i in range(input_rows):

        input_vector = input[i]

        target = targets[i]

        prediction = self.predict(input_vector)

        error = target - prediction

        # Update weights
        gradient_weights = error * prediction * (1 - prediction) * input_vector
        self.weight += learningrate * gradient_weights

        # Update Bias
        gradient_bias = error * prediction * (1 - prediction)
        self.bias += learningrate * gradient_bias


  def evaluate(self, x_test, y_test):
    score = 0

    for input, target in zip(x_test, y_test):

      prediction = self.predict(input)

      if prediction >= 0.5 :
        predicted_class = 1

      else :
        predicted_class = 0

      if predicted_class == target:

        score += 1

    accuracy = score / len(x_test)
    return accuracy



# Dataset Importing and Preprocessing

In [32]:
data = pd.read_csv('/content/drive/MyDrive/Datasets/diabetes_data.csv')

In [33]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [34]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [35]:
data.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [36]:
count_0 = data[data['Outcome'] == 0]
count_0 = count_0.sample(268)
count_1 = data[data['Outcome'] == 1]
count_1 = count_1.sample(268)

In [37]:
count_1.shape

(268, 9)

In [38]:
new_data = pd.concat([count_0, count_1])

In [39]:
new_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
679            2      101             58             17      265  24.2   
68             1       95             66             13       38  19.6   
447            0       95             80             45       92  36.5   
135            2      125             60             20      140  33.8   
347            3      116              0              0        0  23.5   
..           ...      ...            ...            ...      ...   ...   
709            2       93             64             32      160  38.0   
356            1      125             50             40      167  33.3   
539            3      129             92             49      155  36.4   
408            8      197             74              0        0  25.9   
231            6      134             80             37      370  46.2   

     DiabetesPedigreeFunction  Age  Outcome  
679                     0.614   23        0  
68                      0.334   25        0  
447                     0.330   26        0  
135                     0.088   31        0  
347                     0.187   23        0  
..                        ...  ...      ...  
709                     0.674   23        1  
356                     0.962   28        1  
539                     0.968   32        1  
408                     1.191   39        1  
231                     0.238   46        1  

[536 rows x 9 columns]

In [40]:
new_data.Outcome.value_counts()

0    268
1    268
Name: Outcome, dtype: int64

In [41]:
x = new_data.drop('Outcome', axis=1).values
y = new_data['Outcome'].values

In [42]:
x

array([[  2.   , 101.   ,  58.   , ...,  24.2  ,   0.614,  23.   ],
       [  1.   ,  95.   ,  66.   , ...,  19.6  ,   0.334,  25.   ],
       [  0.   ,  95.   ,  80.   , ...,  36.5  ,   0.33 ,  26.   ],
       ...,
       [  3.   , 129.   ,  92.   , ...,  36.4  ,   0.968,  32.   ],
       [  8.   , 197.   ,  74.   , ...,  25.9  ,   1.191,  39.   ],
       [  6.   , 134.   ,  80.   , ...,  46.2  ,   0.238,  46.   ]])

In [43]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [62]:
# Data Spliting into train dataset and testdataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state=42, stratify=y)

In [63]:
# Standardizing the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Model Initialization

In [85]:
perceptron = SigmoidPerceptron(x_train.shape[1])

In [97]:
# weights before Model train
perceptron.weight

array([ 0.05484228,  1.39386037, -0.28160414, -0.53578464,  0.20150939,
        1.03268275,  0.78804078,  0.56431972])

In [98]:
# Model Training
model = perceptron.fit(input=x_train, targets=y_train, learningrate=0.001, epochs=300)

In [99]:
# weights after model Training
perceptron.weight

array([ 0.19518118,  1.38770249, -0.27081362, -0.38437701, -0.00718477,
        0.92682198,  0.64200054,  0.39198876])

In [105]:
# Evaluating on training data
print('Accuracy on training data:', np.round(perceptron.evaluate(x_train, y_train) * 100, 2), '%')

Accuracy on training data: 78.04 %


In [106]:
# Evaluating on training data
print('Accuracy on training data:', np.round(perceptron.evaluate(x_test, y_test) * 100, 2), '%')

Accuracy on training data: 64.81 %
